website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, PInfo
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        print(email)
        user = User.query.filter_by(email=email).first()
        user_info = PInfo.query.filter_by(email=email).first()
        print(user_info)
        if user:
            if user.password == password:
                flash('Logged in successfully', category='success')
                login_user(user, remember=True)
                # user_info = PInfo.query.filter_by(email=email).first()
                # if not user_info:
                print("here")
                return redirect(url_for('views.personal_info'))
                
            else:
                flash('Incorrect password, try again', category='error')
        else:
            # user does not exist
            flash('Email does not exist', category='error')
    return render_template("login_page.html")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash("User already exists", category='error')
        elif len(email) < 4:
            flash("Email invalid", category="error")
        elif len(first_name) < 2:
            flash("First name invalid", category="error")
        elif len(last_name) < 2:
            flash("Last name invalid", category="error")
        elif password1 != password2:
            flash("Passwords must match", category="error")
        elif len(password1) < 7:
            flash("Password must be at least 7 characters", category="error")
        else:
            flash("Account created", category="success")
            #new_user = User(email=email, first_name=first_name, last_name=last_name, password=generate_password_hash(password1, method='pbkdf2:sha256'))
            new_user = User(email=email, first_name=first_name, last_name=last_name, password=password1) #illegal haha
            db.session.add(new_user)
            db.session.commit()
                            
            return redirect(url_for('auth.login'))

        
        
            #something happens
    
    return render_template("sign_up.html")

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from .models import PInfo, User, Trips, trip_participants
import datetime, json
from . import db
from sqlalchemy.sql import select
from website.AI_Generation.generate_gpt import gen_ai_plan

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html")
#"<h1>Test</h1>"

@views.route('/personal_info', methods=['GET', 'POST'])
def personal_info():
    stmt = select(PInfo).where(
        (PInfo.user_id == current_user.id) 
    )
    existing_pinfo = db.session.execute(stmt).fetchone()
    print(existing_pinfo)
    # if not existing_pinfo:
    if request.method == 'POST':
        stmt = select(PInfo).where(
            (PInfo.user_id == current_user.id) 
        )
        existing_pinfo = db.session.execute(stmt).fetchone()
        if not existing_pinfo:
            
            birthday = datetime.datetime.strptime(request.form['birthday'], "%Y-%m-%d")
            location = request.form.get('city')
            gender = request.form.get('gender')
            preferences = json.dumps(request.form.getlist('preferences[]'))
            diet = request.form.get('diet')
            email = current_user.email

            new_pinfo= PInfo(
                user_id = current_user.id, 
                birthday=birthday,
                location=location, 
                gender=gender, 
                preferences=preferences,
                diet=diet,
                email=email
            )
            db.session.add(new_pinfo)
            db.session.commit()
        else:
            return redirect(url_for('views.dashboard'))

    return  render_template("get_personal_info.html", user=current_user)


    # return render_template("get_personal_info.html", user=current_user)
#"<h1>Test</h1>"

@login_required
@views.route('/dashboard')
def dashboard():
    return render_template("dashboard.html", user=current_user)
#"<h1>Test</h1>"

@views.route('/new_trip')
def new_trip():
    return render_template("new_trip.html")
#"<h1>Test</h1>"


@views.route('profile/<string:email>/')
def profile(email):
    user_info = PInfo.query.filter_by(email=email).first()
    user = User.query.filter_by(email=email).first()
    print(user.first_name)
    if user_info:
        return render_template('profile.html', 
            email = user_info.email,
            name = user.first_name + " " + user.last_name,
            birthday = user_info.birthday,
            location = user_info.location,
            gender = user_info.gender,
            preferences = user_info.preferences,
            diet = user_info.diet
        )
    else:
        # If user does not exist, handle accordingly (e.g., display an error message)
        return 'profile not found'
    
    return render_template("profile.html")
#"<h1>Test</h1>"

@views.route('/profile_settings')
def profile_settings():
    return render_template("profile_settings.html")
#"<h1>Test</h1>"

@views.route('/trip')
def trip():
    return render_template("trip.html")

@views.route('/create_new',  methods=['GET', 'POST'])
def create_new():
    print(request.method)
    if request.method == 'POST':
        tripName = request.form.get('tripName')
        startDate = datetime.datetime.strptime(request.form['startDate'], "%Y-%m-%d")
        endDate = datetime.datetime.strptime(request.form['endDate'], "%Y-%m-%d")
        location = request.form.get('location')
        tripType = request.form.get('tripType')
        budget = request.form.get('budget')
        groupLeader_id = current_user.id
        groupLeader_name = current_user.first_name

        print(tripName)
        print(startDate)
        print(endDate)
        print(location)
        print(tripType)
        print(budget)
        print(groupLeader_id)
        print(groupLeader_name)

        new_trip= Trips(
            tripName = tripName,
            groupLeader_id=groupLeader_id,
            groupLeader_name=groupLeader_name, 
            startDate=startDate, 
            endDate=endDate,
            location=location,
            tripType=tripType,
            budget=budget
        )

        db.session.add(new_trip)
        db.session.commit()

        return redirect(url_for('views.trip_detail', trip_id=new_trip.id))
    return render_template("create_new.html", user=current_user)
#"<h1>Test</h1>"

@views.route('/join_group', methods=['GET', 'POST'])
def join_group():
    if request.method == "POST":
        trip_id = request.form['trip_id']
        print(trip_id)
        trip = Trips.query.get(trip_id)
        if trip:
            return redirect(url_for('views.trip_detail', trip_id=trip.id))
        else:
            return "Trip ID does not exist."
    return render_template("join_group.html")

@views.route('/join_group_display', )
def join_group_display():
    return render_template("join_group_display.html")


@views.route('/trip/<int:trip_id>', methods=['GET', 'POST'])
def trip_detail(trip_id):
    if request.method == "POST":
        return redirect(url_for('views.gen_plan', trip_id=trip_id))
    trip = Trips.query.get_or_404(trip_id)
    stmt = select(trip_participants).where(
        (trip_participants.c.user_id == current_user.id) & (trip_participants.c.trip_id == trip.id)
    )
    existing_participant = db.session.execute(stmt).fetchone()
    if not existing_participant:
        new_participant = trip_participants.insert().values(user_id=current_user.id, trip_id=trip.id)
        db.session.execute(new_participant)
        db.session.commit()

    print(trip.participants)
    return render_template(
        'trip.html', 
        trip=trip,
        tripID = trip.id,
        groupLeader = trip.groupLeader_name,
        tripName = trip.tripName,
        startDate = trip.startDate,
        endDate = trip.endDate,
        location = trip.location,
        tripType = trip.tripType,
        budget = trip.budget
    )

    

@views.route('/trip/<int:trip_id>/plan', methods=['GET', 'POST'])
def gen_plan(trip_id):
    #return "hello"
        # 'email': 'lwz900@case.edu',
        # 'location': 'Cleveland',
        # 'birthday': '2008-07-01',
        # 'budget': 1000,
        # 'dietary_restrictions': 'Vegetarian',
        # 'start_date': '2024-11-28',
        # 'end_date': '2024-11-30',
        # 'preferences': ['Creativity', 'Puzzles and Games']

    # stmt = select(Trips).where(
    #     (Trips.id == trip_id)
    # )
    # participants = db.session.execute(stmt).fetchall()
    trip = Trips.query.filter_by(id=trip_id).first()
    print(trip.participants)
    if trip:
        budget = str(trip.budget)
        location = str(trip.location)
        type = str(trip.tripType)
        group_leader_id = trip.groupLeader_id
        group_leader_info = PInfo.query.filter_by(user_id=group_leader_id).first()
        prefs = str(group_leader_info.preferences)
        birthday = str(group_leader_info.birthday)
        response = (gen_ai_plan(budget, location, prefs, birthday))
        return response
    else:
        return None
    
    print(str(participants))
    # print(gen_ai_plan(trip_id))
    return "hwllo"

website/templates/create_new.html
<!DOCTYPE html>
<html>

<head>
    <title>Create new Trip</title>
</head>

<body>
    <h1>Create new Trip</h1>
    <link rel="stylesheet" href="{{ url_for('static', filename='create_new.css') }}" />
    <form method="POST">
        <div>
            <label for="tripName">Trip Name:</label>
            <input type="text" id="tripName" name="tripName" required><br><br>

            <label for="startDate">Start Date:</label>
            <input type="date" id="startDate" name="startDate" required><br><br>

            <label for="endDate">End Date:</label>
            <input type="date" id="endDate" name="endDate" required><br><br>

            <label for="location">Location:</label>
            <input type="text" id="location" name="location" required><br><br>

            <label for="tripType">Trip Type:</label>
            <select id="tripType" name="tripType" required>
                <option value="hangout">Hang Out</option>
                <option value="vacation">Vacation</option>
                <option value="outing">Outing</option>
            </select><br><br>

            <label for="budget">Estimated Budget per Person:</label>
            <input type="number" id="budget" name="budget" required><br><br>

            <button class="loginBtn" type="submit">Submit </button>
        </div>
    </form>

    <div id="randomCode"></div>


</body>

</html>

website/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <style>
        /* Add your custom CSS styles here */
    </style>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}" />

<body>
    <form action="{{ url_for('views.profile', email=user.email) }}" method="get"> 
        <button class=loginBtn type="submit" value="profile">Profile</button>
    </form>
    <form action="{{ url_for('views.new_trip') }}" method="get">
        <button class=loginBtn type="submit" value="new_trip">New Trip</button>
    </form>

    </form>
    <!-- <button id="profile">Profile</button> -->
    <h1>My Travel Buddy Dashboard</h1>
    <h2>Hello {{ user.first_name }}</h2>
    <div id="calendar">
        <!-- Here we are using attributes like
                cellspacing and cellpadding -->
        
        <!-- The purpose of the cellpadding is 
                the space that a user want between
                the border of cell and its contents-->
        
        <!-- cellspacing is used to specify the 
                space between the cell and its contents -->
        <h2 id='currentMonthYear' align="center" style="color: rgb(255, 255, 255);">
            <script>
                const months = [
                        'January', 'February', 'March', 'April',
                        'May', 'June', 'July', 'August',
                        'September', 'October', 'November', 'December'
                    ];

                    const currentDate = new Date();
                    const currentMonth = months[currentDate.getMonth()];
                    const currentYear = currentDate.getFullYear();
                    document.getElementById('currentMonthYear').innerText = `${currentMonth} ${currentYear}`;
            </script>
        </h2>
        <br />
        
        <table class=calendar align="center" cellspacing="21" cellpadding="21">
        
            <!-- The tr tag is used to enter 
                    rows in the table -->
        
            <!-- It is used to give the heading to the
                    table. We can give the heading to the 
                    top and bottom of the table -->
        
            <caption align="top">
                <!-- Here we have used the attribute 
                        that is style and we have colored 
                        the sentence to make it better 
                        depending on the web page-->
            </caption>
        
            <!-- Here th stands for the heading of the
                    table that comes in the first row-->
        
            <!-- The text in this table header tag will 
                    appear as bold and is center aligned-->
        
            <thead>
                <tr>
                    <!-- Here we have applied inline style 
                             to make it more attractive-->
                    <th>Sun</th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thu</th>
                    <th>Fri</th>
                    <th>sat</th>
                </tr>
            </thead>
        
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td>2</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>9</td>
                </tr>
                <tr>
                    <td>10</td>
                    <td>11</td>
                    <td>12</td>
                    <td>13</td>
                    <td>14</td>
                    <td>15</td>
                    <td>16</td>
                </tr>
                <tr>
                    <td>17</td>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                    <td>21</td>
                    <td>22</td>
                    <td>23</td>
                </tr>
                <tr>
                    <td>24</td>
                    <td>25</td>
                    <td>26</td>
                    <td>27</td>
                    <td>28</td>
                    <td>29</td>
                    <td>30</td>
                </tr>
                <tr>
                    <td>31</td>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div id="trips" class=tripbtn>
        <h2>Trips</h2>
        <!-- Add buttons for your trips here -->
        <script>
            // Get the number of trips from the database
            const numberOfTrips = 3; // Replace with actual number of trips
            
            // Generate buttons for each trip
            for (let i = 1; i <= numberOfTrips; i++) {
                const tripButton = document.createElement("button");
                tripButton.textContent = "Trip " + i;
                document.getElementById("trips").appendChild(tripButton);
                tripButton.classList.add("tripbtn");
            }
        </script>
    </div>
    
    <script>
        // Add your JavaScript code here
    </script>
</body>
</html>

website/templates/get_personal_info.html
<!DOCTYPE html>
<html>

<head>
    <title>Create Profile</title>
</head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height= device-height, initial-scale=1.0">
<link rel="stylesheet" href="{{ url_for('static', filename='p_info.css') }}" />

<body>
    <form method="POST">
        <h1>Profile Creation</h1>
        <h2>Welcome {{ user.first_name }}.</h2>
        <div class="textbox">
            <label>Enter your birthday </label>
            <input type="date" id="birthday" name="birthday" placeholder="Enter Birthday">
            </input>
        </div>

        <div class="textbox2">
            <label>Enter your location </label>
            <input type="text" id="city" name="city" placeholder="Enter city">
            </input>
        </div>

        <div class="textbox">
            <label for="gender">Select your gender:</label>
            <select id="gender" name="gender">
                <option value="female">Female</option>
                <option value="male">Male</option>
                <option value="other">Other</option>
            </select>
        </div>
            <div class="textbox2">
                <!-- <form action="/personal_info" method="post"> -->
                <label for="preferences">Select Preferences:</label><br>
                
                <input type="checkbox" id="creativity" name="preferences[]" value="creativity">
                <label for="creativity">Creativity</label><br>
                
                <input type="checkbox" id="outdoor" name="preferences[]" value="outdoor">
                <label for="outdoor">Outdoor</label><br>

                <input type="checkbox" id="relaxation" name="preferences[]" value="relaxation">
                <label for="relaxation">Relaxation</label><br>

                <input type="checkbox" id="adventure" name="preferences[]" value="adventure">
                <label for="adventure">Adventure</label><br>

                <input type="checkbox" id="culture" name="preferences[]" value="culture">
                <label for="culture">Culture</label><br>

                <input type="checkbox" id="food" name="preferences[]" value="food">
                <label for="food">Food</label><br>

                <input type="checkbox" id="nightlife" name="preferences[]" value="nightlife">
                <label for="nightlife">Nightlife</label><br>

                <input type="checkbox" id="shopping" name="preferences[]" value="shopping">
                <label for="shopping">Shopping</label><br>

                <input type="checkbox" id="sports" name="preferences[]" value="sports">
                <label for="sports">Sports</label><br>

                <input type="checkbox" id="entertainment and media" name="preferences[]" value="entertainment and media">
                <label for="entertainment and media">Entertainment and Media</label><br>

                <input type="checkbox" id="learning" name="preferences[]" value="learning">
                <label for="learning">Learning</label><br>

                <input type="checkbox" id="sight-seeing" name="preferences[]" value="sight-seeing">
                <label for="sight-seeing">Sight-seeing</label><br>

                <input type="checkbox" id="gaming and puzzles" name="preferences[]" value="gaming and puzzles">
                <label for="gaming and puzzles">Gaming and Puzzles</label><br>

              </div>
              
            <!-- <input type="submit" value="Submit"> -->
        </div>
        <div class="textbox">
            <label for="diatery restrictions">Select your diatery restrictions:</label>
            <select id="diet" name="diet">
                <option value="none">None</option>
                <option value="vegetarian">Vegetarian</option>
                <option value="vegan">Vegan</option>
                <option value="gluten-free">Gluten-free</option>
                <option value="lactose-free">Lactose-free</option>
                <option value="halal">Halal</option>
                <option value="kosher">Kosher</option>
                <option value="other">Other</option>
            </select>
        </div>

        <button type="submit" value="submit" class="loginBtn">Submit</button>



    </form>
</body>

</html>

website/templates/home.html
<!DOCTYPE html>
<html>

<head>
  <title>My Travel Buddy</title>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}" />

<body>
  
    <form action="{{ url_for('auth.login') }}" method="get">

    <h1>MY TRAVEL BUDDY</h1>
    
    <div class="container">
      
      <div>
        <button type="submit" value="Sign In" class="signin">Login</button>
      </div>

      <div class="textinfo">
        <h2>Your Ultimate Adventure Architect: Where Every Journey Begins!</h2>
        <p>
          Welcome to My Travel Buddy!
          We brainstorm activities and events for your next trip or hangout so that you don't have to.
          Create your perfect trip itinerary with us today!
        </p>
        <input type="submit" value="Plan an Event" class="plan_event">
      </div>
      <img src="static/Logo.png" alt="Logo" class="logo">
    </div>

    
    </form>
  </div>
</body>


</html>

website/templates/join_group.html
<!DOCTYPE html>
<html>

<head>
    <title>Join Group</title>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='join_group.css') }}" />
<body>
    
    <form action="/join_group" method="POST">
        <h1>Join Group</h1>
        <label for="trip_id">Enter Trip ID:</label>
        <input type="text" id="trip_id" name="trip_id">
        <button class = loginBtn type="submit">Join Trip</button>
    </form>
</body>

</html>

website/templates/login_page.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>My Travel Buddy Login</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
        {% for category, message in messages %} 
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endif %} 
        {% endfor %} 
    {% endif %} 
    {% endwith %}

    <form method="POST">
        <h1>Login</h1>
        <link rel="stylesheet" href="{{ url_for('static', filename='login_page.css') }}" />
        <div class="textbox">
            <input 
                type="email" 
                id="email" 
                name="email" 
                placeholder="Enter email">
            </input>
        </div>
        <div class="textbox">
            <input 
                type="password" 
                id="password" 
                name="password" 
                placeholder="Enter password">
            </input>
        </div>
        <button type="submit" value="Login" class="loginBtn">Login</button>
        
        <div class="signup">
            Don't have an account?
            </br>
            <a href="{{ url_for('auth.sign_up') }}">Sign up</a>
        </div>


    </form>
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
    ></script>
</body>

</html>

website/templates/new_trip.html
<!-- FILEPATH: /Users/zhangl/Documents/GitHub/my_travel_buddy/website/templates/new_trip.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Add Trip</title>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='new_trip.css') }}" />
<body>
    
    <h1>Add Trip</h1>
    
  
    
    <form action="{{ url_for('views.create_new') }}" method="get" >
        <button class=loginBtn type="submit" value="create_trip">Create
            New</button>
    </form>
    <form action="{{ url_for('views.join_group') }}" method="get">
        <button class=loginBtn2 type="submit" value="join_group">Join
            Event</button>
    </form>
    
    

</body>
</html>

website/templates/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile</title>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='profile.css') }}" />
<body>
<form method="POST">
    <h1>Profile</h1>
    <div class = signup>
        <h2>Email: {{email}}</h2>
        <h2>Name: {{name}}</h2>
        <h2>Birthday: {{birthday}}</h2>
        <h2>Location: {{location}}</h2>
        <h2>Gender: {{gender}}</h2>
        <h2>Preferences: {{preferences}}</h2>
        <h2>Dietary Restrictions: {{diet}}</h2>
    </div>
    <div>
        <button class = loginBtn id="settingsButton">Settings</button>
    </div>
</form>
</body>
</html>

website/templates/profile_settings.html
<!DOCTYPE html>
<html>

<head>
   <title>User Settings</title>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='profile_settings.css') }}" />
<body>

<form action="/update_profile" method="POST">
    <h1>User Settings</h1>

    <label class = field for="name">Name:</label>
    <input type="text" id="name" name="name" value="John Doe" required> <br>

    <label class = field for="birthday">Birthday:</label>
    <input type="date" id="birthday" name="birthday" value="1990-01-01" required><br>

    <label class = field for="age">Age:</label>
    <input type="number" id="age" name="age" value="30" required><br>

    <label class = field for="location">Location:</label>
    <input type="text" id="location" name="location" value="New York" required><br>

    <label class = field for="gender">Gender:</label>
    <select id="gender" name="gender" required>
        <option value="male">Male</option>
        <option value="female">Female</option>
        <option value="other">Other</option>
    </select><br><br>

    <!-- <form action="/personal_info" method="post"> -->
    <label for="preferences">Select Preferences:</label><br>
    
    <input type="checkbox" id="creativity" name="preferences[]" value="creativity">
    <label for="creativity">Creativity</label><br>
    
    <input type="checkbox" id="outdoor" name="preferences[]" value="outdoor">
    <label for="outdoor">Outdoor</label><br>
    
    <input type="checkbox" id="relaxation" name="preferences[]" value="relaxation">
    <label for="relaxation">Relaxation</label><br>
    
    <input type="checkbox" id="adventure" name="preferences[]" value="adventure">
    <label for="adventure">Adventure</label><br>
    
    <input type="checkbox" id="culture" name="preferences[]" value="culture">
    <label for="culture">Culture</label><br>
    
    <input type="checkbox" id="food" name="preferences[]" value="food">
    <label for="food">Food</label><br>
    
    <input type="checkbox" id="nightlife" name="preferences[]" value="nightlife">
    <label for="nightlife">Nightlife</label><br>
    
    <input type="checkbox" id="shopping" name="preferences[]" value="shopping">
    <label for="shopping">Shopping</label><br>
    
    <input type="checkbox" id="sports" name="preferences[]" value="sports">
    <label for="sports">Sports</label><br>
    
    <input type="checkbox" id="entertainment and media" name="preferences[]" value="entertainment and media">
    <label for="entertainment and media">Entertainment and Media</label><br>
    
    <input type="checkbox" id="learning" name="preferences[]" value="learning">
    <label for="learning">Learning</label><br>
    
    <input type="checkbox" id="sight-seeing" name="preferences[]" value="sight-seeing">
    <label for="sight-seeing">Sight-seeing</label><br>
    
    <input type="checkbox" id="gaming and puzzles" name="preferences[]" value="gaming and puzzles">
    <label for="gaming and puzzles">Gaming and Puzzles</label><br><br>

    
    </select>

    <label for="diatery restrictions">Select your diatery restrictions:</label>
    <select id="diet" name="diet">
        <option value="none">None</option>
        <option value="vegetarian">Vegetarian</option>
        <option value="vegan">Vegan</option>
        <option value="gluten-free">Gluten-free</option>
        <option value="lactose-free">Lactose-free</option>
        <option value="halal">Halal</option>
        <option value="kosher">Kosher</option>
        <option value="other">Other</option>
    </select>

    <button type="submit">Save</button>
</form>
</html>

website/templates/trip.html
<!DOCTYPE html>
<html>

<head>
    <title>{{tripName}}</title>
</head>
<link rel="stylesheet" href="{{ url_for('static', filename='trip.css') }}" />
<body>
    <h1>{{tripName}}</h1>
    <form>
        <div id="tripData">
            <h2>Trip ID: {{tripID}}</h2>
            <h2>Group Leader: {{groupLeader}}</h2>
            <h2>Start Date: {{startDate}}</h2>
            <h2>End Date: {{endDate}}</h2>
            <h2>Location: {{location}}</h2>
            <h2>Trip Type: {{tripType}}</h2>
            <h2>Estimated Budget per Person: {{budget}}</h2>
        </div>
        <h2>Participants:</h2>
        <ul>
            {% for participant in trip.participants %}
            <li>{{ participant.first_name }}</li>
            {% endfor %}
        </ul>
    </form>

    

    <form method="POST">
        <button class="loginBtn" type="submit">Generate Itinerary</button>
    </form>
    
</body>

</html>